
services:
  - type: web
    name: gbairai-pwa
    env: node
    plan: free
    buildCommand: npm run build:render
    startCommand: npm run start:render
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false

databases:
  - name: gbairai-db
    plan: free
